// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018041132_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Sections.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Hero", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.Entities.Sections.Hero", b =>
                {
                    b.OwnsOne("Domain.Entities.Sections.FirstHero", "FirstHero", b1 =>
                        {
                            b1.Property<int>("HeroId")
                                .HasColumnType("int");

                            b1.Property<string>("Image")
                                .HasColumnType("longtext")
                                .HasColumnName("FirstHeroImage");

                            b1.HasKey("HeroId");

                            b1.ToTable("Hero");

                            b1.WithOwner()
                                .HasForeignKey("HeroId");

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "English", b2 =>
                                {
                                    b2.Property<int>("FirstHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("FirstHeroEnglishText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("FirstHeroEnglishTitle");

                                    b2.HasKey("FirstHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("FirstHeroHeroId");
                                });

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "Sinhala", b2 =>
                                {
                                    b2.Property<int>("FirstHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("FirstHeroSinhalaText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("FirstHeroSinhalaTitle");

                                    b2.HasKey("FirstHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("FirstHeroHeroId");
                                });

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "Tamil", b2 =>
                                {
                                    b2.Property<int>("FirstHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("FirstHeroTamilText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("FirstHeroTamilTitle");

                                    b2.HasKey("FirstHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("FirstHeroHeroId");
                                });

                            b1.Navigation("English")
                                .IsRequired();

                            b1.Navigation("Sinhala")
                                .IsRequired();

                            b1.Navigation("Tamil")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.Entities.Sections.SecondHero", "SecondHero", b1 =>
                        {
                            b1.Property<int>("HeroId")
                                .HasColumnType("int");

                            b1.Property<string>("Image")
                                .HasColumnType("longtext")
                                .HasColumnName("SecondHeroImage");

                            b1.HasKey("HeroId");

                            b1.ToTable("Hero");

                            b1.WithOwner()
                                .HasForeignKey("HeroId");

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "English", b2 =>
                                {
                                    b2.Property<int>("SecondHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("SecondHeroEnglishText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("SecondHeroEnglishTitle");

                                    b2.HasKey("SecondHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("SecondHeroHeroId");
                                });

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "Sinhala", b2 =>
                                {
                                    b2.Property<int>("SecondHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("SecondHeroSinhalaText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("SecondHeroSinhalaTitle");

                                    b2.HasKey("SecondHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("SecondHeroHeroId");
                                });

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "Tamil", b2 =>
                                {
                                    b2.Property<int>("SecondHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("SecondHeroTamilText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("SecondHeroTamilTitle");

                                    b2.HasKey("SecondHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("SecondHeroHeroId");
                                });

                            b1.Navigation("English")
                                .IsRequired();

                            b1.Navigation("Sinhala")
                                .IsRequired();

                            b1.Navigation("Tamil")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.Entities.Sections.ThirdHero", "ThirdHero", b1 =>
                        {
                            b1.Property<int>("HeroId")
                                .HasColumnType("int");

                            b1.Property<string>("Image")
                                .HasColumnType("longtext")
                                .HasColumnName("ThirdHeroImage");

                            b1.HasKey("HeroId");

                            b1.ToTable("Hero");

                            b1.WithOwner()
                                .HasForeignKey("HeroId");

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "English", b2 =>
                                {
                                    b2.Property<int>("ThirdHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("ThirdHeroEnglishText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("ThirdHeroEnglishTitle");

                                    b2.HasKey("ThirdHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("ThirdHeroHeroId");
                                });

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "Sinhala", b2 =>
                                {
                                    b2.Property<int>("ThirdHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("ThirdHeroSinhalaText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("ThirdHeroSinhalaTitle");

                                    b2.HasKey("ThirdHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("ThirdHeroHeroId");
                                });

                            b1.OwnsOne("Domain.Entities.Sections.LocalizedContent", "Tamil", b2 =>
                                {
                                    b2.Property<int>("ThirdHeroHeroId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("varchar(500)")
                                        .HasColumnName("ThirdHeroTamilText");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)")
                                        .HasColumnName("ThirdHeroTamilTitle");

                                    b2.HasKey("ThirdHeroHeroId");

                                    b2.ToTable("Hero");

                                    b2.WithOwner()
                                        .HasForeignKey("ThirdHeroHeroId");
                                });

                            b1.Navigation("English")
                                .IsRequired();

                            b1.Navigation("Sinhala")
                                .IsRequired();

                            b1.Navigation("Tamil")
                                .IsRequired();
                        });

                    b.Navigation("FirstHero")
                        .IsRequired();

                    b.Navigation("SecondHero")
                        .IsRequired();

                    b.Navigation("ThirdHero")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
